server:
  port: 8080
   
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/evalart_reto?useSSL=false
    username: dev    
    password: dev
  jpa:
    show-sql: true    
    properties:
      hibernate:
        sql: DEBUG
        type: trace   
  servlet:
    multipart:
      max-file-size: 3MB
      max-request-size: 3MB
      enabled: true
                     